#!/bin/sh

run() {
  if ! pgrep "$1" > /dev/null ;
  then
   "$@"&
  fi
}

run xbanish

run aria2c --rpc-secret="${RPC_SECRET}" -D

run emacs -bg "#17191a" --daemon -fs

run xcape -e "Caps_Lock=Escape"
