#!/bin/sh

run() {
  if ! pgrep "$1" >/dev/null; then
   "$@"&
  fi
}

run pipewire
run pipewire-pulse

run blueman-applet

dbus-update-activation-environment --all

# run dunst

# run foot --server

# run emacs -bg "#17191a" --daemon -fs

# run aria2c --rpc-secret="${RPC_SECRET}" -D
