#!/usr/bin/env zsh

alias cat=bat
alias chts='cht --shell'
dl() {aria2c --no-conf --continue -x16 -s16 -k1M --summary-interval=0 --check-certificate=false "$(wl-paste)"}
alias f=vifm
# alias e="emacs -bg '#1d1f21'"
alias gpg=gpg2
alias jackett='~/.local/bin/Jackett/jackett'
# alias ktlint='ktlint --android --color --relative -v'
alias nightly=/opt/firefox/firefox-bin
alias q=exit
alias reload='exec zsh'
alias s='googler --count 7'
alias x=dtrx
# alias pip='/usr/bin/pip'
alias sudo=doas
alias xargs='xargs ' # Needed for alias subtitution
alias yt=yt-dlp
alias ls='lsd -h'

alias -s {yml,yaml,toml,md}=$EDITOR

forgit_log=fglo
forgit_diff=fgd
forgit_add=fga
forgit_reset_head=fgrh
forgit_ignore=fgi
forgit_restore=fgcf
forgit_clean=fgclean
forgit_stash_show=fgss
