#! /bin/sh

sxhkd &

bspc monitor -d home web term android docs media games social pass dl

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config honor_size_hints true

bspc config normal_border_color "#282c34"
bspc config active_border_color "#282c34"
bspc config focused_border_color "#282c34"

bspc desktop ^2,^3 -l monocle

bspc rule -a Nightly									desktop=^2 state=tiled
bspc rule -a Nightly:Dialog						               state=floating
bspc rule -a Nightly:Devtools									   state=floating
bspc rule -a Nightly:Browser									   state=floating
bspc rule -a Nightly:firefox									   state=floating
bspc rule -a Nightly:Prompt 									   state=floating
bspc rule -a Nm-connection-editor								   state=floating
bspc rule -a "About Firefox Nightly" 							   state=floating
#bspc rule -a alacritty desktop=^3 follow=on
bspc rule -a jetbrains-studio 							desktop=^4 			   center=true
bspc rule -a Anki 										desktop=^5
bspc rule -a okular 									desktop=^5
bspc rule -a calibre 									desktop=^5
bspc rule -a mpv 										desktop=^6 state=floating follow=on center=true layer=above #sticky=on
bspc rule -a PlayOnLinux 								desktop=^7
bspc rule -a Lutris 									desktop=^7
bspc rule -a Steam 						            desktop=^7 state=floating
bspc rule -a Fractal 									desktop=^8
bspc rule -a keepassxc 					            desktop=^9 state=floating
bspc rule -a pcmanfm-qt 										   state=floating center=true
bspc rule -a Thunar 											   state=floating center=true
bspc rule -a ranger 											   state=floating center=true
#bspc rule -a Emacs state=pseudo_tiled
bspc rule -a albert 											   state=floating center=true follow=on
bspc rule -a Yad 												   state=floating
bspc rule -a JDownloader 								desktop=^10
bspc rule -a qBittorrent 								desktop=^10
bspc rule -a feh 												   state=floating

bspc config super mod1
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true

bspc config focus_follows_pointer true

bspc config presel_feedback_color "#888888"
bspc config active_border_color   "#aaaaaa"

# Autostart
wmname LG3D
compton --xrender-sync-fence --xrender-sync --config ~/.config/compton/compton.conf &
feh --randomize --bg-fill ~/Pictures/Wallpapers/
#/usr/bin/emacs --daemon &
#urxvtd &

device_number=$(xinput --list-props "ETPS/2 Elantech Touchpad" | rg "libinput Tapping Enabled" | head -1 | cut -d "(" -f2 | cut -d ")" -f1)
xinput set-prop "ETPS/2 Elantech Touchpad" $device_number 1	# Enable Tapping
numlockx on
#setxkbmap -option "ctrl:swapcaps"
#xset b off &                       # Turn off BELL
light -S 50
xsetroot -cursor_name left_ptr
#xrdb -merge ~/.Xresources &

~/.config/polybar/scripts/launch
