#!/bin/zsh

clip() {
    local selection
    selection=$(
        print 'buffer-cut\nclipboard\nprimary\nsecondary' |
        fzf --preview='xclip -sel {} -o' --bind 'enter:execute(xclip -sel {} -o)' \
            --header 'Select buffer to copy into clipboard')
    echo $selection

}
# -bind 'ctrl-y:execute-silent(echo -n {2..}
