#!/bin/zsh

decode() {
    declare string
    declare base

    if [ "$XDG_SESSION_TYPE" = "x11" ];then
        base=$(xclip -sel clip -o)
    else
        base=$(wl-paste -p)
    fi

    string=$(base64 -d <<< $(echo $base | awk '{$1=$1};1'))

    wl-copy $string
    echo $string
}

decode "$@"
