#!/bin/zsh

decode() {
    declare string
    # string=$(base64 -d <<< $(xclip -sel clip -o | awk '{$1=$1};1'))
    string=$(base64 -d <<< $($1 | awk '{$1=$1};1'))

    wl-copy $string
    # xclip -sel clip <<< $string
    wl-paste $string
}

decode "$@"
