#!/bin/zsh

autoload colors && colors

dl() {
    declare string
    string=$(wl-paste | awk '{$1=$1};1')
    echo "Downloading: \e[4m$fg[blue]$string\e[0m"
    aria2c --continue -x16 -s16 -k1M --summary-interval=0 --check-certificate=false "$@" -- "$string"
}

dl "$@"
