#!/bin/zsh

autoload colors && colors

plain() {
  if (( ! $# )); then
    gocryptfs -q /home/mustaqim/Library/.cipher /home/mustaqim/Library/.plain -o -allow_other
  else
    case $1 in
      hide)
        fusermount -u /home/mustaqim/Library/.plain
        ;;
      show)
        gocryptfs -q /home/mustaqim/Library/.cipher /home/mustaqim/Library/.plain -o -allow_other
        ranger /home/mustaqim/Library/.plain/ & disown
        ;;
      move)
        fd . ~/Library/Downloads/.var -E '*.part' -x mv "{}" ~/Library/.plain/
        ;;
    esac
  fi
}

plain "$@"
