#!/bin/zsh

push() {
     # adb connect 10.0.0.2:5555
     declare -a list
     declare -i i=1
     fd -e mkv -e mp4 -e webm -c always | \
          fzf -m --header $'Send media via adb\n▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔' --header-first | \
          while read -r item; do
               list[$i]=$item
               ((i++))
          done

     adb push $list /sdcard/Movies
}

push "$@"
