#!/bin/zsh

autoload colors && colors

switch_theme() {
    light_theme="WhiteSur-light-solid"
    dark_theme="WhiteSur-dark-solid"
    current_theme=$(gsettings get org.gnome.desktop.interface gtk-theme | tr -d "'")

    light_theme() {
        echo "\nChanging theme to $fg[black]$bg[white]LIGHT"
        gsettings set org.gnome.desktop.interface gtk-theme $light_theme
        gsettings set org.gnome.desktop.interface icon-theme "Papirus-Light"
        kvantummanager --set 'WhiteSur'
        sed -i 's|Papirus-Dark|Papirus-Light|' ~/.config/qt5ct/qt5ct.conf
    }
    dark_theme() {
        echo "\nChanging theme to $fg[black]$bg[white]DARK"
        gsettings set org.gnome.desktop.interface gtk-theme $dark_theme
        gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
        kvantummanager --set 'WhiteSurDark'
        sed -i 's|Papirus-Light|Papirus-Dark|' ~/.config/qt5ct/qt5ct.conf
    }

    case "$1" in
        light)
            light_theme ;;
        dark)
            dark_theme ;;
        toggle)
            [[ $current_theme == $light_theme ]] && dark_theme || light_theme ;;
        *)
            echo "$fg[yellow]Usage: $fg[white]switch_theme [ light | dark | toggle ]"
    esac
}

switch_theme "$@"
