#!/usr/bin/env sh

run() {
  if ! pgrep "$1" > /dev/null ;
  then
   "$@"&
  fi
}


pkill picom; run picom

device_number=$(/usr/bin/xinput --list-props "ETPS/2 Elantech Touchpad" | rg "libinput Tapping Enabled" | head -1 | cut -d "(" -f2 | cut -d ")" -f1)
xinput set-prop 13 "$device_number" 1

numlockx on
setxkbmap -option caps:swapescape
xrdb -load ~/.Xresources
run xbanish
#xset b off
#xsetroot -cursor_name left_ptr

run aria2c --rpc-secret="${RPC_SECRET}" -D

run emacs -bg '#17191a' --daemon

# Run a dock
#run plank

# Netork manager tray icon
#run nm-applet

# Volume icon
#run volumeicon
